# -*- coding: utf-8 -*-
"""modul_penjumlahan.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-zW8NH2UbyeXmBWwGAOdimj0f3FNWlZ3
"""

def penjumlahan(a, b):
    """Fungsi untuk menjumlahkan dua bilangan."""
    jumlah = a + b
    return jumlah